#!/bin/bash
#
# DESCRIPTION:
#
#   Print the artist and song name of the song playing in CMUS or MPD.
#
# DEPENDENCIES:
#
#   CMUS or MPD and MPC
#
# Author: clyde80
# Updated on: September 13, 2017
# Website: https://gitlab.com/clyde80/dotfiles
#
# To file a bug report, create an issue on GitLab:
# https://gitlab.com/clyde80/dotfiles/issues
#
# To submit a bug fix, create a pull request or feature fix, create a merge request:
# https://gitlab.com/clyde80/dotfiles/merge_requests

# Source the config file

# The default location for the config is ~/.config/getmusicstatus/config
. ~/.config/getmusicstatus/config

function get_music_status_cmus() {
    while true; do
        cmus-remote -Q &> /dev/null
        err=$?
        if [[ ${err} == 1 ]]; then
            echo "No Music Playing"
        else
            artist=$(cmus-remote -Q | grep "tag artist ")
            artist=${artist//"tag artist "/""}
            title=$(cmus-remote -Q | grep "tag title")
            title=${title//"tag title "/""}
            echo "> ${artist} - ${title}"
        fi
        sleep ${delay}
    done
}

function get_music_status_mpc() {
    while true; do
        output=$(mpc)
        if [[ -z "${output}" ]]; then
            echo "No Music Playing"
        else
            case ${output} in
                *"paused"*) echo "|| $(mpc | head -1)" ;;
                *)
                    output=$(mpc | head -1)
                    case ${output} in 
                        *"off"*) echo "No Music Playing" ;;
                        *) echo ">${output}" ;;
                    esac
                    ;;
            esac
        fi
        sleep ${delay}
    done
}

case ${use} in
    "cmus") get_music_status_cmus ;;
    "mpv") get_music_status_mpv ;;
    *) echo "Error. Make sure everything is correctly defined" ;;
esac
